run:
	python3 main.py tests/test_data/valid_file.txt

# broken lines with different lengths
bad:
	python3 main.py tests/test_data/bad_format_file.txt

# extra user number 11
bad2:
	python3 main.py tests/test_data/bad_format_file2.txt

# missing user number 10 and 9
bad3:
	python3 main.py tests/test_data/bad_format_file3.txt

empty:
	python3 main.py tests/test_data/empty_file.txt
